// Mock data for the iMovies application

export const movies = [
  {
    id: 1,
    title: "Avengers: Endgame",
    genre: ["Action", "Adventure", "Drama"],
    rating: 8.4,
    duration: 181,
    language: "English",
    poster: "/generic-superhero-team-poster.png",
    backdrop: "/avengers-endgame-backdrop.png",
    releaseDate: "2024-01-15",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and restore order to the universe once and for all.",
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    isNowShowing: true,
  },
  {
    id: 2,
    title: "Spider-Man: No Way Home",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.2,
    duration: 148,
    language: "English",
    poster: "/generic-superhero-movie-poster.png",
    backdrop: "/spiderman-multiverse-backdrop.png",
    releaseDate: "2024-01-20",
    description:
      "Peter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in foes from other Spider-Man movies.",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"],
    trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    isNowShowing: true,
  },
  {
    id: 3,
    title: "The Batman",
    genre: ["Action", "Crime", "Drama"],
    rating: 7.8,
    duration: 176,
    language: "English",
    poster: "/dark-knight-poster.png",
    backdrop: "/gotham-cityscape.png",
    releaseDate: "2024-01-25",
    description:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Jeffrey Wright"],
    trailer: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    isNowShowing: true,
  },
  {
    id: 4,
    title: "Dune: Part Two",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    rating: 8.6,
    duration: 166,
    language: "English",
    poster: "/dune-part-two-poster.png",
    backdrop: "/dune-part-two-desert.png",
    releaseDate: "2024-02-01",
    description:
      "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Josh Brolin"],
    trailer: "https://www.youtube.com/watch?v=Way9Dexny3w",
    isNowShowing: true,
  },
]

export const cinemas = [
  {
    id: 1,
    name: "iMovies Multiplex Downtown",
    location: "Downtown Plaza, 123 Main Street",
    distance: "2.5 km",
    facilities: ["IMAX", "Dolby Atmos", "Recliner Seats", "Food Court"],
    screens: [
      { id: 1, name: "Screen 1", type: "IMAX", capacity: 300 },
      { id: 2, name: "Screen 2", type: "Standard", capacity: 200 },
      { id: 3, name: "Screen 3", type: "Premium", capacity: 150 },
    ],
  },
  {
    id: 2,
    name: "iMovies Mall Central",
    location: "Central Mall, 456 Oak Avenue",
    distance: "4.2 km",
    facilities: ["4DX", "Premium Seats", "Parking", "Restaurant"],
    screens: [
      { id: 4, name: "Screen 1", type: "4DX", capacity: 120 },
      { id: 5, name: "Screen 2", type: "Standard", capacity: 180 },
      { id: 6, name: "Screen 3", type: "Premium", capacity: 160 },
    ],
  },
  {
    id: 3,
    name: "iMovies Westside",
    location: "Westside Complex, 789 Pine Road",
    distance: "6.8 km",
    facilities: ["Dolby Vision", "Luxury Recliners", "VIP Lounge"],
    screens: [
      { id: 7, name: "Screen 1", type: "Premium", capacity: 140 },
      { id: 8, name: "Screen 2", type: "Standard", capacity: 220 },
    ],
  },
]

export const showtimes = [
  // Movie 1 - Avengers: Endgame
  {
    id: 1,
    movieId: 1,
    cinemaId: 1,
    screenId: 1,
    time: "10:00 AM",
    date: "2024-01-15",
    price: 15.99,
    availableSeats: 250,
  },
  {
    id: 2,
    movieId: 1,
    cinemaId: 1,
    screenId: 1,
    time: "2:30 PM",
    date: "2024-01-15",
    price: 18.99,
    availableSeats: 180,
  },
  {
    id: 3,
    movieId: 1,
    cinemaId: 1,
    screenId: 1,
    time: "7:00 PM",
    date: "2024-01-15",
    price: 21.99,
    availableSeats: 120,
  },
  {
    id: 4,
    movieId: 1,
    cinemaId: 2,
    screenId: 5,
    time: "11:30 AM",
    date: "2024-01-15",
    price: 14.99,
    availableSeats: 160,
  },
  {
    id: 5,
    movieId: 1,
    cinemaId: 2,
    screenId: 5,
    time: "6:30 PM",
    date: "2024-01-15",
    price: 19.99,
    availableSeats: 90,
  },

  // Movie 2 - Spider-Man: No Way Home
  {
    id: 6,
    movieId: 2,
    cinemaId: 1,
    screenId: 2,
    time: "12:00 PM",
    date: "2024-01-20",
    price: 16.99,
    availableSeats: 170,
  },
  {
    id: 7,
    movieId: 2,
    cinemaId: 1,
    screenId: 2,
    time: "4:45 PM",
    date: "2024-01-20",
    price: 19.99,
    availableSeats: 140,
  },
  {
    id: 8,
    movieId: 2,
    cinemaId: 1,
    screenId: 2,
    time: "8:30 PM",
    date: "2024-01-20",
    price: 22.99,
    availableSeats: 85,
  },
  {
    id: 9,
    movieId: 2,
    cinemaId: 3,
    screenId: 7,
    time: "1:15 PM",
    date: "2024-01-20",
    price: 17.99,
    availableSeats: 120,
  },

  // Movie 3 - The Batman
  {
    id: 10,
    movieId: 3,
    cinemaId: 2,
    screenId: 6,
    time: "3:00 PM",
    date: "2024-01-25",
    price: 18.99,
    availableSeats: 130,
  },
  {
    id: 11,
    movieId: 3,
    cinemaId: 2,
    screenId: 6,
    time: "7:45 PM",
    date: "2024-01-25",
    price: 21.99,
    availableSeats: 95,
  },
  {
    id: 12,
    movieId: 3,
    cinemaId: 3,
    screenId: 8,
    time: "5:30 PM",
    date: "2024-01-25",
    price: 16.99,
    availableSeats: 180,
  },

  // Movie 4 - Dune: Part Two
  {
    id: 13,
    movieId: 4,
    cinemaId: 1,
    screenId: 1,
    time: "1:00 PM",
    date: "2024-02-01",
    price: 20.99,
    availableSeats: 200,
  },
  {
    id: 14,
    movieId: 4,
    cinemaId: 1,
    screenId: 1,
    time: "6:15 PM",
    date: "2024-02-01",
    price: 23.99,
    availableSeats: 150,
  },
  {
    id: 15,
    movieId: 4,
    cinemaId: 2,
    screenId: 4,
    time: "4:00 PM",
    date: "2024-02-01",
    price: 25.99,
    availableSeats: 80,
  },
]

export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    isAdmin: false,
    bookings: [],
  },
  {
    id: 2,
    name: "Admin User",
    email: "admin@imovies.com",
    phone: "+1234567891",
    isAdmin: true,
    password: "admin123", // Added password for admin user
    bookings: [],
  },
]

export const bookings = [
  {
    id: 1,
    userId: 1,
    movieId: 1,
    cinemaId: 1,
    showtimeId: 1,
    seats: ["A1", "A2"],
    totalAmount: 31.98,
    bookingDate: "2024-01-10",
    status: "confirmed",
  },
]

export const reviews = [
  {
    id: 1,
    userId: 1,
    movieId: 1,
    rating: 5,
    comment: "Amazing movie! The visual effects were spectacular and the story was emotionally satisfying.",
    date: "2024-01-16",
    userName: "John Doe",
  },
  {
    id: 2,
    userId: 1,
    movieId: 2,
    rating: 4,
    comment: "Great movie with excellent action sequences. The multiverse concept was handled well.",
    date: "2024-01-21",
    userName: "John Doe",
  },
  {
    id: 3,
    userId: 2,
    movieId: 1,
    rating: 4,
    comment: "Incredible conclusion to the saga. Some pacing issues but overall fantastic.",
    date: "2024-01-17",
    userName: "Admin User",
  },
  {
    id: 4,
    userId: 2,
    movieId: 3,
    rating: 5,
    comment: "Dark and gritty take on Batman. Robert Pattinson was excellent.",
    date: "2024-01-26",
    userName: "Admin User",
  },
]
